### ISSUE TITLE
fisherman?

### ISSUE THREAD

**Issue by ghost** [wk/plugin-ssh-term-helper#1]
Hi @wk, I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to fisherman:
• https://github.com/fisherman/fisherman/issues/69#issuecomment-179661994

I'm willing to help with anything. Cheers.

**Comment by wk** [comment]
@brj Thanks for the heads-up! Fisherman seems pretty great, and has a very minimalistic architecture which I like.

I notice that at the moment, you [seem to](https://github.com/fisherman/fisherman/blob/master/fisher.fish#L1021) rely on the Github API to fetch all the repositories under `oh-my-fish` and `fisherman` users to build an index of themes and plugins.

Is there a package registry for external repositories foreseen (and how would one go about getting included in it?), or is the new model such that you create additional repositories under fisherman/ on request for plugin contributors?

**Comment by ghost** [comment]
@wk Good question. Yeah, there's a concept of "players" (it's just an array), which are basically users or orgs that host a large number of plugins. But there's also an [index](https://github.com/fisherman/index), used to power up the [online](http://fisherman.sh) search. I don't know if we should depend on that index to power up the CLI too, as I am actually thinking of shutting down the search, and just host the AsciiCast on the website.

Easiest is to join the fisherman org and add your own repos there tho (which you are totally encouraged to do and that's how we grow members). Want to hop in?

**Comment by wk** [comment]
@brj, There are many reasons for plug-in authors to prefer making plug-ins available from their own repositories rather than repositories under a single "aggregation" org:
- Allows a single authoritative distribution point for multiple plugin management frameworks
- Allows distributing plug-ins which may be licensed under unusual licenses
- Prevents the plug-in from disappearing in the next licensing/attribution war (a la omf).
- Clearly ties plug-in and author, pads author's "Github presence"

Discoverability of plug-ins is the purpose of the "list" command in the plug-in management framework, which can display the plug-in summary, and perhaps a URL in a verbose mode to allow a perspective user to review the documentation.

I've modified the repository name from pkg-ssh-term-helper to plugin-ssh-term-helper, modified the documentation to be generic with fisherman examples (as opposed to only omf), and submitted a pull request against Fisherman's [Index](https://github.com/fisherman/index/pull/79).

P.S.

I _think_ if you wanted an easier, more "Github native" way to manage 3rd party hosted plug-ins, you could create a single fisherman/3rd-party repository, consisting of directories which are all git remotes to other repositories instead. That would avoid the necessity of maintaining the Index.

**Comment by ghost** [comment]
Thanks for taking the time to submit the pkg to the index!

**Comment by wk** [comment]
@brj, Thanks for the heads-up and the commit, and success with making fisherman awesome!

Closing this issue.
