### ISSUE TITLE
Not enough emojis 😠

### ISSUE THREAD

**Issue by Neels-v-Wyk** [wk/plugin-ssh-term-helper#2]
I am very angry 😠 at the obvious lack 🤷 of consideration for the culture 🧫 of the new generation 👪. Please 🙏 add more emojis 😂😂😂 so as not to discriminate 🤔 against us.

**Comment by wk** [comment]
Thank you for the issue! It's always a pleasure to learn of new users of ssh-term-helper and their unique use cases.

In order to make progress on this issue, could you perhaps provide some additional detail that could make it easier to determine the best way forward here? Specifically, it'd be interesting to know:

* Which emoji are the best candidates for inclusion, and which if any should be avoided?
* Where should these emoji be present? Is the project description welcoming enough as-is, or would that be a candidate? Perhaps in the README.md, or in the comments of the fish script itself would be best?
* Have you considered the interaction between emoji and alternative output methods through which GitHub as well as this specific project could be accessed? For example, do emoji render correctly on braille terminals? This might help identify the optimal way to incorporate emoji into this project without inconveniencing other users.

**Comment by wk** [comment]
@Neels-v-Wyk Is this issue still relevant, or have emoji gone out of fashion?
